### ISSUE TITLE
1080P display is downsizing

### ISSUE THREAD

**Issue by sbrooke** [mrothenbuecher/Chromecast-Kiosk#10]
I'm chromecasting a Grafana dashboard to a 1080P TV through a Gen1 Chromecast.  The page is not displaying like a 1920x1080 pixel size.  It appears to be closer to 720P.  I'm not sure if this is a capability reporting problem on the pull from Grafana or on the push to the Chromecast.  The TV believes it's operating at 1080P.

**Comment by mrothenbuecher** [comment]
The problem here is that the chromecast decides which resolution he will put to the screen. I think it is a know issue. I had the same Issue on a [samsung ](http://www.samsung.com/de/support/model/UE40K5579SUXZG) tv. I changed the source of hdmi port to pc. Suddenly it worked.
