### ISSUE TITLE
Cronjob URL - Extra "+" added at the end

### ISSUE THREAD

**Issue by dbruneau-ie** [mrothenbuecher/Chromecast-Kiosk#12]
When I create a cronjob, the resulting URL's always seem to have a "+" at the end.  Because of this they won't load/resolve correctly on the chromecast and I end up with a white screen.

If I use the "start cast" interface, the same URL will load properly.

Windows x64
Tomcat 8.0

War from github releases; 0.3 (44fa8b3)

Example:
![image](https://user-images.githubusercontent.com/9416894/31019277-248de58c-a4fd-11e7-853a-8ba6c6cd0a17.png)

Thank you for this project.  Very simple/clean and gets the job done.

**Comment by mrothenbuecher** [comment]
I fixed the error with the plus but this should not be the problem. Is the webserver you try to display in your LAN? Did you try to use the ip adress instead of the servername?

**Comment by dbruneau-ie** [comment]
Thanks for the fix.

I was testing the possibility of loading "published" google sheets.  Essentially a spreadsheet that is turned into a compiled static web page.  It is from an external server.  So using a domain name and not an IP.

I had noticed in some documentation that you mention using IP addresses instead of servername for local servers.  Is this because of the chromecast's embedded DNS server setting?  From what I'm seeing loading external/internet servers seems to work rather well.

**Comment by mrothenbuecher** [comment]
Published google sheets work as far as I know. We use it in our company. For this use case we use the embedded link which looks something like this https://docs.google.com/presentation/.../embed?start=true&loop=true&delayms=15000 .

I once stumbled that the cast couldn't reach a local server by name but by the IP address.

**Comment by mrothenbuecher** [comment]
@dbruneau-ie is the issue solved?

**Comment by dbruneau-ie** [comment]
Appologies for the lack of feedback.  I haven't had a chance to re-test with your updated code.  I'm not at all familiar with tomcat and compiling packages, and haven't had the time to learn it yet to create the waf with the updated code.

However, if the "+" on cron jobs isn't there anymore, then they will work for us.

Thanks again,

----
Just to expand more on the "by name vs IP" issue, I believe all chromecasts bypass local DNS servers and go straight to Googles public DNS servers to lookup hostnames.  This means that chromecasts can't resolve local hostnames, hence why giving the IP of the server fixes the issue.  No DNS lookup required.
