### ISSUE TITLE
Add RPiCast capability

### ISSUE THREAD

**Issue by sbrooke** [mrothenbuecher/Chromecast-Kiosk#13]
Feature request to add RPiCast capability.  The RPi W is much less expensive than a Chromecast, but isn't able to act as a ChromeCast receiver.  It would be nice to extend the functionality of this to support the RPiCast receiver since they don't have something like this on the RPiCast side.

**Comment by mrothenbuecher** [comment]
Hi @sbrooke is there a java api?

**Comment by sbrooke** [comment]
Don't know.  I'm not familiar with that side of it.  Just saw it as a ChromeCast "like" service that's available on the RPi platform.  ChromeCast itself is not available as a receiver on the RPi.

**Comment by mrothenbuecher** [comment]
Sorry would not be possible. As long as there is no java api.
