### ISSUE TITLE
Problems displaying from Grafana

### ISSUE THREAD

**Issue by sbrooke** [mrothenbuecher/Chromecast-Kiosk#14]
First, this tool has been awesome!  I've used it for several years now, displaying a Grafana dashboard in kiosk mode through a gen1 CC.

I'm updating to a new Grafana server and rebuilding my dashboard.  The new server is on Grafana v6.6.2 and the old one is v5.4.2.  Trying to cast to any CC in the house on the new version now presents only a white screen.  If I cast from a Chrome browser it works fine.  If I cast the old dashboard it works fine.

Something in Grafana v6.6.2 isn't working right with the kiosk.  I'm not sure if it's a page formatting problem that Chrome browser now understands.

Any ideas?

**Comment by mrothenbuecher** [comment]
Hi there,

do you use the name of the machine or the ip address in the url?

**Comment by sbrooke** [comment]
IP in all cases. This is all internal for me and I’m not using any dns.

**Comment by mrothenbuecher** [comment]
Mhhh strange, I've to look up if there is a way of debugging. For me it looks like there is a Issue with the chromecast receiver app.

**Comment by rez0n** [comment]
It is seems Grafana nginx configuration issue, check webserver logs, it block client by some reason.
As woraround you can try to use nginx proxy like this https://github.com/rez0n/docker-nginx-iframe-proxy

**Comment by mrothenbuecher** [comment]
@sbrooke did you try @rez0n Solution?

**Comment by sbrooke** [comment]
I have not yet.  I may get to it this weekend.
