### ISSUE TITLE
Cronjob SSL handshake terminated by remote host

### ISSUE THREAD

**Issue by ghost** [mrothenbuecher/Chromecast-Kiosk#31]
After running cronjobs for a while the server loses connection with the Chromecast and starts erroring out. The web interface can't connect to it at all. Restarting the server fixes the issue. Funnily enough restarting the Chromecast also works. 

`chromecast-kiosk-setup  | 12:23:00.002 [cron4j::scheduler[3c06d14a79eeb2873113954a0000018185c3fb0c32307248]::executor[3
c06d14a79eeb287641881be0000018186374ca24806140f]] INFO  de.michaelkuerbis.presenter.utils.CronJob - task crontest started
chromecast-kiosk-setup  | 12:23:00.012 [cron4j::scheduler[3c06d14a79eeb28771de92ed0000018185c4dbe46ed13c0d]::executor[3
c06d14a79eeb2872e0f68060000018186374ca132e81065]] ERROR de.michaelkuerbis.presenter.utils.CronJob - javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
chromecast-kiosk-setup  | 12:23:00.012 [cron4j::scheduler[3c06d14a79eeb28771de92ed0000018185c4dbe46ed13c0d]::executor[3
c06d14a79eeb2872e0f68060000018186374ca132e81065]] INFO  de.michaelkuerbis.presenter.utils.CronJob - task crontest succeeded
chromecast-kiosk-setup  | 12:23:00.013 [cron4j::scheduler[3c06d14a79eeb2873113954a0000018185c3fb0c32307248]::executor[3
c06d14a79eeb287641881be0000018186374ca24806140f]] ERROR de.michaelkuerbis.presenter.utils.CronJob - javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
chromecast-kiosk-setup  | 12:23:00.014 [cron4j::scheduler[3c06d14a79eeb2873113954a0000018185c3fb0c32307248]::executor[3
c06d14a79eeb287641881be0000018186374ca24806140f]] INFO  de.michaelkuerbis.presenter.utils.CronJob - task crontest succeeded`

On the network level Keep-Alive's, SYN's, ACK's and PSH's seem to be flowing normally but when it comes to sending the job to the Chromecast only RST's are sent. In my particular case 8 of them for one cronjob.
Also the amount of packets seem to go way up. After a few hours of running the average amount of TCP packets sent between the server and the Chromecast is around 100 per second. Normally it seems to be around 3 per second.

I compiled the .war-file myself from the latest source code. Getting a new release out could be beneficial since I'm guessing it uses a vulnerable version of Log4j.

Thanks for the project though! It's been very interesting to research.

**Comment by mrothenbuecher** [comment]
Hi,

under the hood chromecast-kiosk uses [chromecast-java-api-v2](https://github.com/vitalidze/chromecast-java-api-v2), therefore I am not able to help you. Sorry Mate.
