### ISSUE TITLE
Show URL or title of page being cast

### ISSUE THREAD

**Issue by JeroenBakker** [mrothenbuecher/Chromecast-Kiosk#7]
It would be great if in the overview under the current app of a chromecast, you'd be able to see exactly what's being cast in the form of a title or URL of a web page.
When everything is labeled as "chromecast-kiosk-web" it doesn't really tell you that much.

The problem is, I'm not sure if it's even possible to pass such information along to or from a chromecast.

Just noticed this is possibly a duplicate of #6

**Comment by mrothenbuecher** [comment]
You are right it would be a great feature. I already tried once but, as you mentioned, for me it seems not to be possible possible to pass this information.

But I'll keep this issue open. Thanks mate!

**Comment by JeroenBakker** [comment]
You would think it's possible since this information is freely available when using Chrome's own interface for casting tabs (assuming they use all the same APIs as we do).

**Comment by mrothenbuecher** [comment]
If i get [this](https://github.com/googlecast/CastHelloText-chrome/blob/master/receiver.html#L74) right there is a way to exchange messages. I'll will give it a try in my spare time.

**Comment by mrothenbuecher** [comment]
with d82b7f1 done

**Comment by JeroenBakker** [comment]
Great! Thanks for the speedy implementation of this enhancement.
