### ISSUE TITLE
Update presenter.war

### ISSUE THREAD

**Issue by JeroenBakker** [mrothenbuecher/Chromecast-Kiosk#8]
It seems like the presenter.war is 8 months old, and there have been features added since.
I tried to build a new one myself, but didn't succeed.

I'm mainly looking to use the cronjob feature to schedule casting of pages.

**Comment by mrothenbuecher** [comment]
updated presenter.war with d82b7f1

try it out

**Comment by JeroenBakker** [comment]
Thanks, everything seems to work just fine.
Haven't had a chance to see the cronjobs in action since I've only just set them up. but I assume they'll work just fine of course.

There do seem to be two buttons "default" and "info" for every chromecast that don't actuelly seem to do anything other than show a message saying "change done", is this intentional and I'm just not noticing the effects or did a partially implemented feature make its way into this build?

**Comment by mrothenbuecher** [comment]
These two buttons toggle just a "grouping" feature.

In the default group you can put all the chromecasts you want. All the casts in this group can started with on click. (start casts -> set the checkbox). All the casts which does belong to the info group won't be started.

**Comment by JeroenBakker** [comment]
Ah I see, thanks for the clarification.
As the presenter.war is definitely updated, I'll close this issue :)
